name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of timo-reymann/deterministic-zip
        run: echo "latest_version=$(curl -Lso /dev/null -w %{url_effective} https://github.com/timo-reymann/deterministic-zip/releases/latest | grep -o '[^/]*$')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Pull base repo timo-reymann/deterministic-zip
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: timo-reymann/deterministic-zip
          path: deterministic-zip
          fetch-depth: 1
          ref: ${{ env.latest_version }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: deterministic-zip/
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/deterministic-zip-docker:latest , ${{ secrets.DOCKERHUB_USERNAME }}/deterministic-zip-docker:${{ env.latest_version }}
